#pragma once

#include <chrono>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

// Header-only PLY logger. Šablona předpokládá, že SampleType má členy x,y,z,intensity,ftime,rtime,ring.
template<typename SampleType>
class PLYLogger {
public:
    explicit PLYLogger(std::string base_dir = "/data/robot/lidar")
        : base_dir_(std::move(base_dir))
    {
    }

    void dump(const SampleType* samples, std::size_t count)
    {
        if (count == 0) {
            return;
        }

        const std::string path = makePlyPath();
        std::ofstream ofs(path);
        if (!ofs) {
            std::cerr << "[PLYLogger] failed to open PLY file: " << path << "\n";
            return;
        }

        ofs << "ply\n";
        ofs << "format ascii 1.0\n";
        ofs << "comment generated by PLYLogger\n";
        ofs << "element vertex " << count << "\n";
        ofs << "property float x\n";
        ofs << "property float y\n";
        ofs << "property float z\n";
        ofs << "property float intensity\n";
        ofs << "property double ftime\n";
        ofs << "property double rtime\n";
        ofs << "property uint32 ring\n";
        ofs << "end_header\n";

        ofs << std::setprecision(7) << std::fixed;
        for (std::size_t i = 0; i < count; ++i) {
            const SampleType &p = samples[i];
            ofs << p.x << " "
                << p.y << " "
                << p.z << " "
                << p.intensity << " "
                << p.ftime << " "
                << p.rtime << " "
                << p.ring << "\n";
        }
    }

private:
    std::string makePlyPath() const
    {
        using clock = std::chrono::system_clock;

        const auto now = clock::now();
        const auto ms  = std::chrono::duration_cast<std::chrono::milliseconds>(
                             now.time_since_epoch()) % 1000;

        std::time_t tt = clock::to_time_t(now);
        std::tm tm{};
#if defined(_WIN32)
        localtime_s(&tm, &tt);
#else
        localtime_r(&tt, &tm);
#endif

        std::ostringstream date_ss;
        date_ss << std::put_time(&tm, "%Y-%m-%d");

        std::ostringstream hour_ss;
        hour_ss << "points-" << std::setw(2) << std::setfill('0') << tm.tm_hour;

        std::ostringstream file_ss;
        file_ss << "ply-"
                << std::setw(2) << std::setfill('0') << tm.tm_min << "-"
                << std::setw(2) << std::setfill('0') << tm.tm_sec << "-"
                << std::setw(3) << std::setfill('0') << ms.count()
                << ".ply";

        std::filesystem::path dir = std::filesystem::path(base_dir_) / date_ss.str() / hour_ss.str();
        std::filesystem::create_directories(dir);

        std::filesystem::path path = dir / file_ss.str();
        return path.string();
    }

    std::string base_dir_;
};
